version: '3.8'

on:
  push:
    branches:
      - main  # Trigger CI/CD only when pushing to the main branch

services:
  app:
    image: techiemithlesh/evergreen-app:latest
    container_name: evergreen_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .env:/var/www/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "${PORT:-8080}:80"  # Uses PORT env variable, defaults to 8080 To fix
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_evergreen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
